[project]
name = "gh-tokengen"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.3",
    "prompt-toolkit>=3.0.52",
    "pyjwt>=2.10.1",
    "rapidfuzz>=3.14.3",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
]
